# Define from what image we want to build from. Here we will use the latest LTS (long term support) version 8 of node
FROM node:8

# set environment
ENV NODE_ENV=development
RUN echo $NODE_ENV

# Install nodemon
RUN npm install -g nodemon

RUN ls -la
# Set working dir
WORKDIR app
RUN ls -la


# command to run your app using CMD
CMD ["nodemon", "src/index.js"]
EXPOSE 9000
